[platformio]
default_envs = waveshare_esp32_s3_lcd_147

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.arduino.memory_type = qio_opi
board_build.partitions = huge_app.csv
lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  bblanchon/ArduinoJson@^7.0.4

[env:waveshare_esp32_s3_lcd_147]
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=3
  -DUSER_SETUP_LOADED
  -DST7789_DRIVER
  -DTFT_WIDTH=172
  -DTFT_HEIGHT=320
  -DTFT_MOSI=45
  -DTFT_SCLK=40
  -DTFT_CS=42
  -DTFT_DC=41
  -DTFT_RST=39
  -DTFT_BL=48
  -DTFT_BACKLIGHT_ON=HIGH
  -DTFT_RGB_ORDER=TFT_BGR
  -DUSE_HSPI_PORT
  -DSPI_FREQUENCY=40000000
  -DLOAD_GLCD
  -DLOAD_FONT2
  -DLOAD_FONT4
  -DSMOOTH_FONT
  -DRAGNAR_GATEWAY_DISPLAY=1

[env:waveshare_esp32_s3_lcd_147_no_display]
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=3
  -DRAGNAR_GATEWAY_DISPLAY=0
